#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

version: 2
updates:
- package-ecosystem: maven
  directory: "/chutney/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  labels:
  - dependencies
