# Changelog template

changelog:
  categories:
    - title: '⚡ Breaking changes:'  
      labels:
        - breaking
    - title: '🚀 Implemented enhancements:'  
      labels:
        - enhancement
    - title: '🐛 Fixed bugs:' 
      labels:
        - bug
    - title: '🔧 Technical enhancements:' 
      labels:
        - technical
    - title: '👒 Dependencies:' 
      labels:
        - dependencies
    - title: 'to categorize manually:'
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - enhancement
          - bug
          - technical
          - breaking
          - release
