{
 "title": "Scenarios executions",
 "description": "Scenario and campaigns executions overview",
 "tags": [ "exec" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Scenarios executions",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(scenario_execution_count_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ARXIV",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(scenarioStatus) (scenario_in_campaign_gauge{campaignId=\"667500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAPI",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(scenarioStatus) (scenario_in_campaign_gauge{campaignId=\"666500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHUTNEY",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(scenarioStatus) (scenario_in_campaign_gauge{campaignId=\"665500\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}