#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

name: 'build example'
description: 'build example'
inputs:
  goals:
    default: "clean install -V -B"
    description: "Maven goals to execute"
  cache-artifacts:
    default: ""
    description: "path of artifacts to be cached"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Build Example
      shell: bash
      run: |
        cd ./example
        echo "Running: ${{inputs.goals}}"
        mvn ${{inputs.goals}}
        cd ..

    - name: Temporarily cache jar artifacts
      if: inputs.cache-artifacts != ''
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifacts
        path: ${{inputs.cache-artifacts}}
        retention-days: 1
        overwrite: true
