spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: false
  datasource:
    url: jdbc:postgresql://localhost:10457/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
