#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

FROM squidfunk/mkdocs-material
RUN pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-redirects
