name: "Build all"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build-all-template.yml
    with:
      skipTests: ${{ startsWith(github.head_ref, 'release/') }}
