name: "Chutney Dependency Convergence"

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'chutney/**'

defaults:
  run:
    working-directory: ./chutney

jobs:
  convergence-chutney:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven_cache
      - name: Build with Maven
        run: mvn -B -V validate -Dconvergence -fae
