name: "Publish Documentation"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

defaults:
  run:
    working-directory: ./docs

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-redirects
      - run: mkdocs gh-deploy --force
